### ISSUE TITLE
Could you provide the data preprocessing code for weighted adjacency matrix?

### ISSUE THREAD

**Issue by jeongwhanchoi** [hazdzz/Road_Traffic_Flow_datasets_from_DCRNN#1]
I would like to compare the data processing method with the Bing Yu's STGCN method.
I wanna know which dataset uses the weighted adj preprocessing like Bing Yu's STGCN.
Because as i know, it seems that the weighted adj preprocessing is only used in his paper.

His paper's datasets are PEMS-07(M & L), but do we need to pre-process the adj in PEMS-BAY and METR-LA???

**Comment by hazdzz** [comment]
Sorry, I cannot offer the preprocess code, because the code has been deleted after I pushed the dataset to GitHub.

**Comment by jeongwhanchoi** [comment]
> Sorry, I cannot offer the preprocess code, because the code has been deleted after I pushed the dataset to GitHub.

Thank you for reply.
Then do you use the code which is from this function below? or same setting?

https://github.com/VeritasYin/STGCN_IJCAI-18/blob/6ea78b908ed53e7e773a555a97cabf2ad1818fb5/utils/math_graph.py#L71

**Comment by hazdzz** [comment]
No. I use the formula from ChebyNet.

**Comment by jeongwhanchoi** [comment]
Thanks :)
 It seems both are same concept

**Comment by hazdzz** [comment]
The formula in STGCN paper is different from ChebyNet.
